spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true